### ISSUE TITLE
not saving server address or credentials

### ISSUE THREAD

**Issue by csjjpm** [MediaBrowser/Emby.Roku#110]
Hi,
  I've sideloaded this on a Now TV 2 device.  It does not store my remote server address or credentials.  In preferences 'Remember User: Yes [default]'.
  Hopefully you can help.
thanks
Paul

**Comment by LukePulverenti** [comment]
I can't reproduce this, but one to possibly try is uninstalling all emby channels and then reinstalling. It's possible the app is using too much storage space and thus the save operation is failing. It's something we'll be looking into. Thanks.
